safe: true
lsi: false
pyments: true
markdown: redcarpet
redcarpet:
  extensions: ["hard_wrap",
               "no_intra_emphasis",
               "tables",
               "fenced_code_blocks",
               "autolink",
               "strikethrough",
               "lax_spacing",
               "space_after_headers",
               "with_toc_data",
               "xhtml"]
